# Generated by Django 3.2 on 2022-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('aspi_id', models.AutoField(db_column='ASPI_ID', primary_key=True, serialize=False)),
                ('aspi_primernombre', models.CharField(db_column='ASPI_PRIMERNOMBRE', max_length=100)),
                ('aspi_segundonombre', models.CharField(blank=True, db_column='ASPI_SEGUNDONOMBRE', max_length=100, null=True)),
                ('aspi_primerapellido', models.CharField(db_column='ASPI_PRIMERAPELLIDO', max_length=100)),
                ('aspi_segundoapellido', models.CharField(blank=True, db_column='ASPI_SEGUNDOAPELLIDO', max_length=100, null=True)),
                ('aspi_correo', models.CharField(db_column='ASPI_CORREO', max_length=50)),
                ('aspi_genero', models.CharField(db_column='ASPI_GENERO', max_length=10)),
                ('tipodocumento_id', models.IntegerField(db_column='TIPODOCUMENTO_ID')),
                ('aspi_numerodocumento', models.CharField(db_column='ASPI_NUMERODOCUMENTO', max_length=20)),
                ('aspi_rh', models.CharField(db_column='ASPI_RH', max_length=3)),
                ('aspi_numerocelular', models.CharField(blank=True, db_column='ASPI_NUMEROCELULAR', max_length=10, null=True)),
                ('aspi_telefonocasa', models.CharField(blank=True, db_column='ASPI_TELEFONOCASA', max_length=10, null=True)),
                ('aspi_estado', models.CharField(db_column='ASPI_ESTADO', max_length=1)),
                ('aspi_ciudadnacimiento', models.IntegerField(db_column='ASPI_CIUDADNACIMIENTO')),
                ('aspi_ciudadexpediciondocumento', models.IntegerField(db_column='ASPI_CIUDADEXPEDICIONDOCUMENTO')),
                ('aspi_ciudadresidencia', models.IntegerField(db_column='ASPI_CIUDADRESIDENCIA')),
                ('aspi_direccion', models.CharField(db_column='ASPI_DIRECCION', max_length=255)),
                ('aspi_fechacambio', models.DateField(auto_now_add=True, db_column='ASPI_FECHACAMBIO')),
            ],
            options={
                'db_table': 'ASPIRANTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convocatoriainscripcion',
            fields=[
                ('coin_id', models.AutoField(db_column='COIN_ID', primary_key=True, serialize=False)),
                ('coin_fechainicio', models.DateField(db_column='COIN_FECHAINICIO')),
                ('coin_fechafin', models.DateField(db_column='COIN_FECHAFIN')),
                ('coin_nombre', models.CharField(db_column='COIN_NOMBRE', max_length=255)),
                ('coin_numerocupos', models.IntegerField(db_column='COIN_NUMEROCUPOS')),
                ('coin_fechacambio', models.DateField(auto_now_add=True, db_column='COIN_FECHACAMBIO')),
            ],
            options={
                'db_table': 'CONVOCATORIAINSCRIPCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('grup_id', models.AutoField(db_column='GRUP_ID', primary_key=True, serialize=False)),
                ('grup_nombre', models.CharField(db_column='GRUP_NOMBRE', max_length=100)),
                ('grup_descripcion', models.CharField(db_column='GRUP_DESCRIPCION', max_length=255)),
                ('grup_cantidad', models.IntegerField(db_column='GRUP_CANTIDAD')),
                ('grup_fechacambio', models.DateField(auto_now_add=True, db_column='GRUP_FECHACAMBIO')),
            ],
            options={
                'db_table': 'GRUPOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('hora_id', models.AutoField(db_column='HORA_ID', primary_key=True, serialize=False)),
                ('hora_horario', models.CharField(db_column='HORA_HORARIO', max_length=100)),
                ('hora_fechacambio', models.DateField(auto_now_add=True, db_column='HORA_FECHACAMBIO')),
            ],
            options={
                'db_table': 'HORARIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('idio_id', models.AutoField(db_column='IDIO_ID', primary_key=True, serialize=False)),
                ('idio_nombre', models.CharField(blank=True, db_column='IDIO_NOMBRE', max_length=255, null=True)),
                ('idio_descripcion', models.CharField(db_column='IDIO_DESCRIPCION', max_length=255)),
                ('idio_estado', models.CharField(db_column='IDIO_ESTADO', max_length=1)),
                ('idio_fechacambio', models.DateField(auto_now_add=True, db_column='IDIO_FECHACAMBIO')),
            ],
            options={
                'db_table': 'IDIOMA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('insc_id', models.AutoField(db_column='INSC_ID', primary_key=True, serialize=False)),
                ('insc_estadoinscripcion', models.CharField(db_column='INSC_ESTADOINSCRIPCION', max_length=255)),
                ('insc_fechainscripcion', models.DateField(db_column='INSC_FECHAINSCRIPCION')),
                ('insc_fechacambio', models.DateField(auto_now_add=True, db_column='INSC_FECHACAMBIO')),
            ],
            options={
                'db_table': 'INSCRIPCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('nive_id', models.AutoField(db_column='NIVE_ID', primary_key=True, serialize=False)),
                ('nive_nombre', models.CharField(db_column='NIVE_NOMBRE', max_length=50)),
                ('nive_numeronivel', models.CharField(db_column='NIVE_NUMERONIVEL', max_length=10)),
                ('nive_duracion', models.CharField(db_column='NIVE_DURACION', max_length=100)),
                ('nive_descripcion', models.CharField(db_column='NIVE_DESCRIPCION', max_length=255)),
                ('nive_code', models.CharField(db_column='NIVE_CODE', max_length=10)),
                ('nive_fechacambio', models.DateField(auto_now_add=True, db_column='NIVE_FECHACAMBIO')),
            ],
            options={
                'db_table': 'NIVELES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodoacademico',
            fields=[
                ('peac_id', models.AutoField(db_column='PEAC_ID', primary_key=True, serialize=False)),
                ('peac_fechainicio', models.DateField(db_column='PEAC_FECHAINICIO')),
                ('peac_fechafin', models.DateField(db_column='PEAC_FECHAFIN')),
                ('peac_ano', models.DateField(db_column='PEAC_ANO')),
                ('peac_descripcion', models.CharField(db_column='PEAC_DESCRIPCION', max_length=255)),
                ('peac_fechacambio', models.DateField(auto_now_add=True, db_column='PEAC_FECHACAMBIO')),
            ],
            options={
                'db_table': 'PERIODOACADEMICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('salo_id', models.AutoField(db_column='SALO_ID', primary_key=True, serialize=False)),
                ('salo_nombre', models.CharField(db_column='SALO_NOMBRE', max_length=100)),
                ('salo_bloque', models.CharField(db_column='SALO_BLOQUE', max_length=100)),
                ('salo_fechacambio', models.DateField(auto_now_add=True, db_column='SALO_FECHACAMBIO')),
            ],
            options={
                'db_table': 'SALON',
                'managed': False,
            },
        ),
    ]
